export const SET_TITLE = 'SET_TITLE';
export const SET_OPTION_MENU_ITEMS = 'SET_OPTION_MENU_ITEMS';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';

export const DUMMY_ACTION = 'DUMMY_ACTION';
export const CLEAR_DUMMIES = 'CLEAR_DUMMIES';