export const SET_TITLE = 'SET_TITLE';
export const SET_OPTION_MENU_ITEMS = 'SET_OPTION_MENU_ITEMS';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';

// Socket.IO
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const APPEND_MESSAGE = 'APPEND_MESSAGE';
